# Generated by Django 4.1.7 on 2023-02-27 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_aboutus_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('issue_link', models.CharField(max_length=200)),
            ],
        ),
    ]
