# Generated by Django 4.1.7 on 2023-03-03 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_product_productservice_productservicepivot'),
    ]

    operations = [
        migrations.AddField(
            model_name='productservice',
            name='product_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.product'),
        ),
        migrations.DeleteModel(
            name='ProductServicePivot',
        ),
    ]
