# Generated by Django 4.1.7 on 2023-03-10 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_productservice_product_id_delete_productservicepivot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('resourcers', models.CharField(max_length=200)),
                ('logo', models.CharField(max_length=250)),
            ],
        ),
    ]
