# Generated by Django 4.1.7 on 2023-03-10 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='resourcers',
            new_name='resources',
        ),
    ]
