# Generated by Django 4.1.7 on 2023-03-24 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_resourcers_company_resources'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200)),
                ('whatsapp', models.CharField(max_length=200)),
                ('cellphone', models.TextField()),
                ('email', models.TextField()),
                ('images', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FormContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.TextField()),
                ('contactway', models.TextField(blank=True, null=True)),
                ('message', models.TextField()),
                ('countrycode', models.CharField(max_length=4)),
                ('phonenumber', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('consultdate', models.DateField(blank=True, null=True)),
                ('formtype', models.CharField(choices=[('question', 'Question'), ('consultation', 'Consultation')], max_length=30)),
                ('costumertype', models.CharField(choices=[('personal', 'Personal'), ('business', 'Business')], max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TechCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TechService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TechPivotTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.techcategory')),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.techservice')),
            ],
        ),
    ]
